# Backend e Desempenho
unredir-if-possible = true;
backend = "glx";
vsync = true;
#glx-no-stencil = true;
use-damage = true;
detect-client-opacity = true;
detect-rounded-corners = true;
detect-client-leader = true;

# Sombras
shadow = true;
shadow-radius = 10;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.4;
shadow-red = 0.066;
shadow-green = 0.066;
shadow-blue = 0.105;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Plank'",
  "name = 'Plank'",
  "class_g = 'Cortile'",
  "class_g = 'cortile'",
  "class_g = 'xfce4-notifyd'",
  "_GTK_FRAME_EXTENTS@:c",
  "_GTK_FRAME_EXTENTS@",
  "window_type = 'splash'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'menu'",
  "window_type = 'tooltip'",
  "class_g = 'resolve'"
];

# Cantos Arredondados
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'menu'",
  "window_type = 'tooltip'",
  "class_g = 'Plank'",
  "class_g = 'Cortile'",
  "class_g = 'cortile'",
  "window_type = 'desktop'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_VERT'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_HORZ'",
  "fullscreen"
];

# Transição e Animações
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [
  "class_g = 'Cortile'"
];

# Transparência
active-opacity = 1.0;
inactive-opacity = 0.95;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "100:class_g = 'firefox'",
  "100:class_g = 'Plank'",
  "100:class_g = 'Cortile'",
  "100:fullscreen"
];

# Desfoque
blur-method = "dual_kawase";
blur-strength = 3;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'menu'",
  "window_type = 'tooltip'",
  "class_g = 'Plank'",
  "class_g = 'xfce4-screenshooter'",
  "class_g = 'Cortile'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c",
  "_GTK_FRAME_EXTENTS@",
  "window_type = 'splash'",
  "class_g = 'resolve'"
];

# Tipos de Janelas Específicos
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.95; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-output = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 1.0; shadow = false; full-shadow = false; };
  dropdown_menu = { opacity = 1.0; shadow = false; full-shadow = false; };
  menu = { opacity = 1.0; shadow = false; };
};
